### ISSUE TITLE
not work any more

### ISSUE THREAD

**Issue by egoo3** [GitHub30/gdrive.sh#12]
"status": "QUEUED",
  "percentDone": 1,
    "status": "COUNTING",
  "percentDone": 100,
    "status": "FAILED",
  "percentDone": 100,
    "status": "FAILED",
  "percentDone": 100,
    "status": "FAILED",
  "percentDone": 100,
    "status": "FAILED",
  "percentDone": 100,
    "status": "FAILED",
  "percentDone": 100,
    "status": "FAILED",
  "percentDone": 100,

**Comment by GitHub30** [comment]
I'm sorry please use gdown

```bash
# download a file
gdown https://drive.google.com/uc?id=1l_5RK28JRL19wpT22B-DY9We3TVXnnQQ
# for a Folder
gdown --folder https://drive.google.com/drive/u/0/folders/18EunmjOJsbE5Lh9zA0cZ4wKV6Um46dkg
```

https://colab.research.google.com/drive/1QXVAkUovvIQva65TuvAcca_jRhR_M6Bc?usp=sharing
